apiVersion: v1
kind: Pod
metadata:
  name: testpod
spec:
  containers:
    - name: testpod
      image: ccr.ccs.tencentyun.com/devopsvip/busybox:1.30
      args:
        [
          /bin/sh,
          -c,
          'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done',
        ]
